### PR TITLE
pull

### PR DESCRIPTION
**Pull request by Pannycakes**

### CODE REVIEW

**Comment by chris30269** [comment]
get my recent changes to exrx.js and do it like that. you'll have to also touch data.js to make your body parts and muscles exist

**Review by chris30269 — CHANGES_REQUESTED** [review]
basically, if it's the name of something, it needs to come from somewhere else

**Comment by Pannycakes** [comment]
fuk u

**Comment by chris30269** [comment]
OK

**Comment by Pannycakes** [comment]
luv u

**Review by chris30269 — APPROVED** [review]

**Pull request merged**
